name: Build Branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
    steps:

      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: "Build"
        run: chmod 755 gradlew && ./gradlew build

        # Populates ARTIFACTORY_USERNAME and ARTIFACTORY_API_KEY with
        # temporary username/password for publishing to packages.atlassian.com
      - name: Get publish token
        id: publish-token
        if: github.ref == 'refs/heads/release'
        uses: atlassian-labs/artifact-publish-token@v1.0.1
        with:
          output-modes: environment

      # Publishes to Artifactory only on push to the "release" branch.
      - name: "Publish"
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        if: github.ref == 'refs/heads/release'
        run: chmod 755 gradlew && ./gradlew artifactoryPublish
